name: Build J2V8

on: [push]

jobs:
  j2v8_macos:
    name: Build J2V8 for macOS
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Download monolithic libraries and extract to v8.out directory
      run: |
        curl -O https://download.eclipsesource.com/j2v8/v8/libv8_7.4.288_monolith.zip
        mkdir -p v8.out
        unzip libv8_7.4.288_monolith.zip -d v8.out

        # start j2v8 build
        python build.py -t macos -a x64 j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java j2v8test

    - name: Archive J2V8 Linux x86_64 jar
      uses: actions/upload-artifact@v1.0.0
      with:
        name: j2v8-macos-x86_64
        path: build.out/j2v8_macos_x86_64-6.0.0-SNAPSHOT.jar