name: Build J2V8

on: [push]

jobs:
  generate_j2v8_archives:
    name: Create J2V8 Linux jar and Android aar archive files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build V8 and J2V8 for Linux
      run: |
        # start j2v8 build
        python2 build.py -t linux -a x64 --docker v8 j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java j2v8test

    - name: Archive J2V8 Linux x86_64 jar
      uses: actions/upload-artifact@v1.0.0
      with:
        name: j2v8-linux-x86_64
        path: build.out/j2v8_linux_x86_64-6.2.0.jar
